#!/usr/bin/env python3
"""What must be true before `bdtools update` will move a tool — and what must
never silently block or silently drop.

Two failures, both found live on 2026-09-15 when `update all` reported
"FAILED to update: irma_gui genoflu_gui":

1. REGENERATED BYTECODE BLOCKED EVERY UPDATE. irma_gui and genoflu_gui carry
   __pycache__/*.pyc committed upstream. The interpreter rewrites those on
   import, so the checkout went dirty the first time anyone RAN the tool, and
   tool_blocking_edits then refused the force checkout forever:

       ERROR irma_gui has local source changes:
             backend/app/__pycache__/__init__.cpython-310.pyc

   This is the frontend/dist defect one layer down — that function's own
   docstring records it — except worse, because dist needs a build to go dirty
   and bytecode needs only a launch. It hit every user on every platform.

2. THE RETRY COMMAND DROPPED TOOLS. The failure summary printed
   `bin/bdtools update irma_gui genoflu_gui`, but check-updates.sh reads
   TARGET="${ARGS[0]:-all}" — one target. The second name was collected and
   ignored, so the suite handed out an instruction it would not carry out, and
   the user believed both tools had been retried. bdtools' own
   cmd_check_updates made it worse by forwarding only "$1", so the extra
   argument never even reached the script that could object to it.
"""
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMMON = ROOT / "bin/lib/common.sh"
BDTOOLS = ROOT / "bin/bdtools"


def sh(script, env=None):
    full = f'set -euo pipefail\nsource "{COMMON}"\n{script}\n'
    e = dict(os.environ)
    e.pop("DRY_RUN", None)
    if env:
        e.update(env)
    return subprocess.run(["bash", "-c", full], capture_output=True, text=True,
                          env=e)


def git(*args, cwd):
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True)


class BlockingEditsTests(unittest.TestCase):
    """tool_blocking_edits: regenerable output must not block; source must."""

    def setUp(self):
        self.td = tempfile.TemporaryDirectory()
        self.addCleanup(self.td.cleanup)
        self.repo = Path(self.td.name) / "tool"
        (self.repo / "backend/app/__pycache__").mkdir(parents=True)
        (self.repo / "frontend/dist").mkdir(parents=True)
        git("init", "-q", cwd=self.repo)
        git("config", "user.email", "t@example.com", cwd=self.repo)
        git("config", "user.name", "t", cwd=self.repo)
        # Committed exactly as the real tool repos do it: bytecode in git.
        (self.repo / "backend/app/__init__.py").write_text("x = 1\n")
        (self.repo / "backend/app/__pycache__/__init__.cpython-310.pyc").write_bytes(b"\x00old")
        (self.repo / "frontend/dist/index.html").write_text("<html>old</html>")
        git("add", "-A", cwd=self.repo)
        git("commit", "-qm", "initial", cwd=self.repo)

    def _blocking(self):
        r = sh(f'tool_blocking_edits "{self.repo}"')
        self.assertEqual(r.returncode, 0, r.stderr)
        return [l for l in r.stdout.splitlines() if l.strip()]

    def test_a_clean_checkout_blocks_nothing(self):
        self.assertEqual(self._blocking(), [])

    def test_regenerated_bytecode_does_not_block(self):
        # THE REGRESSION: this is what merely launching the tool does.
        (self.repo / "backend/app/__pycache__/__init__.cpython-310.pyc").write_bytes(b"\x00new")
        self.assertEqual(self._blocking(), [],
                         "bytecode is rewritten on import; blocking on it makes "
                         "a tool un-updatable the moment someone runs it")

    def test_a_real_source_edit_still_blocks(self):
        # The guard must keep doing its job: the .py beside the .pyc is exactly
        # what a user edit looks like, and it must still stop a force checkout.
        (self.repo / "backend/app/__init__.py").write_text("x = 2\n")
        self.assertEqual(self._blocking(), ["backend/app/__init__.py"])

    def test_a_source_edit_is_reported_even_alongside_stale_bytecode(self):
        # The realistic shape: editing a .py and running the tool touches both.
        # Tolerating the bytecode must not swallow the edit that matters.
        (self.repo / "backend/app/__init__.py").write_text("x = 3\n")
        (self.repo / "backend/app/__pycache__/__init__.cpython-310.pyc").write_bytes(b"\x00new")
        self.assertEqual(self._blocking(), ["backend/app/__init__.py"])

    def test_the_frontend_tolerance_is_unchanged(self):
        (self.repo / "frontend/dist/index.html").write_text("<html>new</html>")
        self.assertEqual(self._blocking(), [])


class SingleTargetTests(unittest.TestCase):
    """A tool name must never be accepted and then ignored."""

    def _run(self, *args):
        return subprocess.run([str(BDTOOLS), *args],
                              capture_output=True, text=True, timeout=300)

    def test_two_tools_are_refused_not_silently_truncated(self):
        r = self._run("check-updates", "irma_gui", "genoflu_gui")
        self.assertNotEqual(r.returncode, 0)
        out = r.stdout + r.stderr
        self.assertIn("one tool at a time", out)

    def test_the_refusal_suggests_a_command_per_tool(self):
        r = self._run("check-updates", "irma_gui", "genoflu_gui")
        out = r.stdout + r.stderr
        self.assertIn("bin/bdtools check-updates irma_gui", out)
        self.assertIn("bin/bdtools check-updates genoflu_gui", out,
                      "the second tool is the one that used to vanish")

    def test_the_suggestion_names_the_verb_actually_used(self):
        r = self._run("update", "irma_gui", "genoflu_gui", "--dry-run")
        out = r.stdout + r.stderr
        self.assertIn("bin/bdtools update genoflu_gui", out)
        self.assertNotIn("bin/bdtools check-updates genoflu_gui", out)

    def test_one_tool_is_still_accepted(self):
        r = self._run("check-updates", "irma_gui")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("irma_gui", r.stdout)

    def test_no_argument_still_means_all(self):
        # cmd_check_updates forwards "$@" now; the default must survive that.
        r = self._run("check-updates")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("vsnp_gui", r.stdout)
        self.assertIn("genoflu_gui", r.stdout)

    def test_the_failure_summary_cannot_print_a_multi_tool_update(self):
        # The summary builds its retry hint from the FAILED list. Printing them
        # on one `bdtools update` line is now a command the CLI refuses, so the
        # hint has to be one line per tool.
        src = (ROOT / "bin/check-updates.sh").read_text()
        self.assertNotIn('bin/bdtools update ${FAILED[*]}', src)
        self.assertIn('for _f in "${FAILED[@]}"', src)


if __name__ == "__main__":
    unittest.main()
